version: '3.8'

services:
  web:
    build: .
    # command: bash -c "python ats/manage.py migrate && python ats/manage.py runserver 0.0.0.0:8000"
    command: bash ats/ats/start_server.sh
    volumes:
      - .:/usr/src/ats
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
#     depends_on:
#       - db
#   db:
#     image: postgres:13-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_USER=hello_django
#       - POSTGRES_PASSWORD=hello_django
#       - POSTGRES_DB=hello_django_dev

# volumes:
#   postgres_data:
