# Generated by Django 5.0.4 on 2024-04-09 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HRManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HRManagerPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_applicant', models.BooleanField(default=False)),
                ('create_applicant', models.BooleanField(default=False)),
                ('accept_reject_applicant', models.BooleanField(default=False)),
                ('update_notes', models.BooleanField(default=False)),
                ('hr_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.hrmanager')),
            ],
        ),
    ]
